name: checklists
maintainer: Steven Vandevelde <icid.asset@gmail.com>


dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - flow
  - icidasset-template
  - lucid
  - protolude
  - record-hasfield
  - shikensu
  - tagsoup == 0.14.*
  - text
  - time
  - unordered-containers
  - yaml
  - xml == 1.3.*


executables:
  # 🚜
  build:
    main: Main.hs
    source-dirs:
      - src
      - system/Build


default-extensions:
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - ExtendedDefaultRules
  - NoImplicitPrelude
  - OverloadedStrings


ghc-options:
  - "-F -pgmF=record-dot-preprocessor"
